### ISSUE TITLE
onSave config not working

### ISSUE THREAD

**Issue by joelmoss** [manuelpuyol/vscode-erb-linter#7]
Because erb-lint is slow it causes a delay when saving a file. So I want to disable running it on save, but setting `"erb.erb-lint.onSave": false` does not disable it. erb-lint still runs on save.

**Comment by manuelpuyol** [comment]
Hi @joelmoss, thanks for the report!

I think you may be talking about autocorrection on save here, right?
If that's the case, you should change the language specific config:

```json
"[erb]": {
  "editor.defaultFormatter": "manuelpuyol.erb-linter",
  "editor.formatOnSave": false
}
```

Maybe the configuration names are a bit confusing... `erb.erb-lint.onSave` is supposed to control whether or not erblint should run _in the background_ on save, which will add the warnings in the editor (non-blocking).
Autocorrection is controlled by `editor.formatOnSave`, which will delay saving until erblint runs and updates the file

**Comment by joelmoss** [comment]
ah right. thx
