### ISSUE TITLE
Erb lint not working on given executePath and configFilePath together

### ISSUE THREAD

**Issue by javaharut** [manuelpuyol/vscode-erb-linter#8]
When giving `erb.erb-lint.executePath` and `erb.erb-lint. configFilePath` it stops running. 

if there is no cinfig file path erb-lint works fine

**Comment by pmpinto** [comment]
Just in case it helps anyone else, the path that `executePath` is expecting is not what `gem which erb_lint` outputs.

In my case:
```bash
$ gem which erb_lint
/Users/pedro/.rvm/gems/ruby-3.1.0/gems/erb_lint-0.4.0/lib/erb_lint.rb
```

The path `executePath` is expecting is:
```
/Users/pedro/.rvm/gems/ruby-3.1.0/gems/erb_lint-0.4.0/exe
```

**Comment by cmmille** [comment]
> Just in case it helps anyone else, the path that `executePath` is expecting is not what `gem which erb_lint` outputs.
> 
> In my case:
> 
> ```shell
> $ gem which erb_lint
> /Users/pedro/.rvm/gems/ruby-3.1.0/gems/erb_lint-0.4.0/lib/erb_lint.rb
> ```
> 
> The path `executePath` is expecting is:
> 
> ```
> /Users/pedro/.rvm/gems/ruby-3.1.0/gems/erb_lint-0.4.0/exe
> ```

@manuelpuyol This would be super useful to have in the readme for the extension!

To get the extension to work properly for me with a globally installed `erb-lint` here is my workspace config file:
```json
{
  "[erb]": {
    "editor.defaultFormatter": "manuelpuyol.erb-linter",
    "editor.formatOnSave": true
  },
  "erb.erb-lint.executePath": "/opt/rubies/ruby-2.7.8/bin/"
}
```

For reference, here is the output of `which erblint`
```bash
/opt/rubies/ruby-2.7.8/bin/erblint
```
